"""add app state

Revision ID: 617912995956
Revises: 1b190b43cf70
Create Date: 2026-09-25 18:01:44.307223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617912995956'
down_revision: Union[str, Sequence[str], None] = '1b190b43cf70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_workspace_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_state')
    # ### end Alembic commands ###
