"""add prompt response

Revision ID: c1e16d3fd5a8
Revises: 532a7aa8c0de
Create Date: 2026-10-04 07:04:24.133193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e16d3fd5a8'
down_revision: Union[str, Sequence[str], None] = '532a7aa8c0de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('response', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'response')
    # ### end Alembic commands ###
