"""replace components with tools

Revision ID: f4ad3039b481
Revises: b18c726f46fb
Create Date: 2026-09-26 17:23:45.139171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ad3039b481'
down_revision: Union[str, Sequence[str], None] = 'b18c726f46fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('domain', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('ui_type', sa.String(length=50), nullable=False),
    sa.Column('available_actions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_tools',
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('tool_id', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'tool_id')
    )
    op.drop_table('workspace_components')
    op.drop_table('components')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_components',
    sa.Column('workspace_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('component_id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'component_id')
    )
    op.drop_table('workspace_tools')
    op.drop_table('tools')
    # ### end Alembic commands ###
